pipeline {
    agent any

    environment {
        MAINTAINER="DPM"
    }

    stages {
        stage('Checkout') {
           environment {
                LOCAL_VAR_CHECK="LOCAL_VALUE"
            }
            steps {
                script {
                    def gitRepoUrl = 'https://github.com/Djimi/OnlineShop.git'
                    checkout scmGit(
                    branches: [[name: 'main']],
                    userRemoteConfigs: [[url: gitRepoUrl]])
                }
            }
        }

        stage('Basic information') {
            steps {
                echo 'Maintainer is: ${MAINTAINER}'
            }
        }

        stage('Build') {
            steps {
                echo 'Building..'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}